name: Orderbook Subgraph CI
on: [push]
env:
  THE_GRAPH_API_TOKEN: ${{ secrets.THE_GRAPH_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: install npm dependencies
        run: |
          nix-shell --run init

      - name: Build Docker Compose images
        run: |
          nix-shell --run docker-down
          nix-shell --run docker-up

      - name: Run Subgraph tests
        run: nix-shell --run ci-test

      - name: Stop containers
        run: nix-shell --run docker-down
  deploy-mumbai:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/25-04-2023-26060fa8e7b97f9a488edb3a4e161448e7aa2b98-signedContext'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: install npm dependencies
        run: |
          nix-shell --run init

      - name: Graph Deployments mumbai
        run: nix-shell --run "ts-node scripts/deploy.ts --contractAddress 0x00fb875f4d86c9c73e0176a6d244047a069ce53d --subgraphName rainprotocol/orderbook-mumbai --network mumbai --graphAccessToken $THE_GRAPH_API_TOKEN"

  deploy-polygon:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/25-04-2023-26060fa8e7b97f9a488edb3a4e161448e7aa2b98-signedContext'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: install npm dependencies
        run: |
          nix-shell --run init

      - name: Graph Deployments polygon
        run: nix-shell --run "ts-node scripts/deploy.ts --contractAddress 0xed6ca29bf4af0c247ad5a865cb5ce1ec905429ce --subgraphName rainprotocol/orderbook-polygon --network matic --graphAccessToken $THE_GRAPH_API_TOKEN"