name: Orderbook Subgraph CI
on: [push]
env:
  THE_GRAPH_API_TOKEN: ${{ secrets.THE_GRAPH_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: install npm dependencies
        run: nix-shell --run init

      - name: Build Docker Compose images
        run: nix-shell --run docker-up

      - name: Run Subgraph tests
        run: nix-shell --run ci-test

      - name: Stop containers
        run: nix-shell --run docker-down

  deploy-ethereum:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: install npm dependencies
        run: nix-shell --run init

      - name: Graph deploy ethereum
        run: nix-shell --run "ts-node scripts/deploy.ts --contractAddress 0xce0a4f3e60178668c89f86d918a0585ca80e0f6d --subgraphName rainprotocol/orderbook-ethereum --network mainnet --blockNumber 17140914 --graphAccessToken $THE_GRAPH_API_TOKEN --skipCheck"

      - name: Graph deploy polygon
        run: nix-shell --run "ts-node scripts/deploy.ts --contractAddress 0x2de560ED9Ba8a6CDFe92e26862Ecb86e6e2d9705 --subgraphName rainprotocol/orderbook-sloshy --network matic --blockNumber 41785697 --graphAccessToken $THE_GRAPH_API_TOKEN --skipCheck"

      - name: Graph deploy NHS BOT
        run: nix-shell --run "ts-node scripts/deploy.ts --contractAddress 0xdd42ed000da6716044db223a0f9e6f02e6c86af3 --subgraphName rainprotocol/orderbook-0xdd42ed000da6716044 --network matic --blockNumber 42605680 --graphAccessToken $THE_GRAPH_API_TOKEN --skipCheck"
